name: Latest Github activities
on:
  schedule:
    # Runs every 5 minutes
    - cron: "0/5 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-github-activity:
    name: Update this repo's README with latest github activities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
