name: Latest github activities
on:
  schedule:
    # Runs every 30 minutes
    - cron: "*/10 * * * *"

jobs:
  update-readme-github-activities:
    name: Update this repo's README latest github activities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: ""
          gh_token: ${{secrets.GITHUB_TOKEN}}
